import Head from "next/head";
import { Layout, Card, Col, Row } from "antd";
import { Header } from "../components/Header";
import Link from "next/link";
import axios from "axios";

const { Meta } = Card;

export default function Home({ items, NODE_ENV }) {
  return (
    <>
      <Head>
        <title>F5 Test - 모두의 테스트</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header NODE_ENV={NODE_ENV} />
        <Layout className="site-layout">
          <Row className="mt-8 mb-24 px-4" gutter={[4, 4]}>
            {items.map((item, key) => (
              <Col
                xs={12}
                sm={12}
                md={8}
                lg={8}
                xl={8}
                xxl={8}
                key={key}
                className="pb-6"
              >
                <Link href={`/start/${item.link}`} target="_blank">
                  <Card
                    hoverable
                    size="small"
                    height={400}
                    cover={
                      <img
                        alt={item.title}
                        src={item.logo}
                        width={320}
                        height={320}
                      />
                    }
                  >
                    <Meta title={<h2 className="text-sm">{item.title}</h2>} />
                  </Card>
                </Link>
              </Col>
            ))}
          </Row>
        </Layout>
      </main>
    </>
  );
}

export const getServerSideProps = async () => {
  const res = await axios.get(`${process.env.BASE_API_URL}/test/list`);
  return { props: { items: res.data, NODE_ENV: process.env.NODE_ENV } };
};
